#ifndef CONSTANTS_H
#define CONSTANTS_H

#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 128
#define SCALE 6
#define FRAMERATE 12
#define PI 3.1415926535

enum KEYS { NONE, LEFT, RIGHT, UP, DOWN, X };
enum TEXTURES { TILE_TXT, BLANK_TXT, GRASS_TXT };
enum ANIMAATIONS { GRASS_ANIM };

#endif
